import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {Button, FeedBox, NumberInput, TextInput} from "wemixplay-ui";

import 'wemixplay-ui/styles.css';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
    <FeedBox media={[{type:"youtube", src: 'https://www.youtube.com/watch?v=73cRdT3Rb1A&list=PLd6mSd18EoVK-L_7_blmOZWIQVIxN6jYt&index=34'}]} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <NumberInput />
        <TextInput />
        awdawd
        <Button>Click</Button>
      </main>
    </>
  );
}
