name: Publish to npm

on:
  push:
    tags:
      - 'npm-publish/*'

jobs:
  publish:
    runs-on: self-hosted 

    steps:
      - name: Get tag name
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/npm-publish/}" >> $GITHUB_ENV

      - name: Checkout tag 
        uses: actions/checkout@v3
        with:
          ref: refs/tags/npm-publish/${{ env.TAG_VERSION }}

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.DEREK_NPM_TOKEN }}" > ./.npmrc

      - name: Install dependencies
        run: yarn --ignore-platform

      - name: Publish to npm
        run: yarn publish --new-version ${{ env.TAG_VERSION }}

      - name: Delete tag remotely
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WP_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true

      - name: Cleanup .npmrc
        run: rm -f ./.npmrc

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
