name: Publish to npm

on:
  push:
    tags:
      - 'npm-publish/*'

jobs:
  publish:
    runs-on: self-hosted 

    steps:
      - name: Get tag name
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/npm-publish/}" >> $GITHUB_ENV

      - name: Print TAG_VERSION
        run: echo "TAG_VERSION = ${{ env.TAG_VERSION }}"

      - name: Checkout tag 
        uses: actions/checkout@v3
        with:
          ref: refs/tags/npm-publish/${{ env.TAG_VERSION }}

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/wemixplay-ui/:_authToken=${{ secrets.DEREK_NPM_TOKEN }}" > ./.npmrc

      - name: Install dependencies
        run: yarn --ignore-platform

      - name: Publish to npm
        run: yarn publish --new-version ${{ env.TAG_VERSION }}

      - name: Delete tag remotely
        env:
          GITHUB_TOKEN: ${{ secrets.WP_GITHUB_TOKEN }}
        run: git push https://${GH_TOKEN}@github.com/${{ github.repository }} :refs/tags/npm-publish/${{ env.TAG_VERSION }}

      - name: Cleanup .npmrc
        run: rm -f ./.npmrc

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
