name: Publish to npm

on:
  push:
    tags:
      - 'npm-publish/*'

jobs:
  publish:
    runs-on: self-hosted 

    env:
      TAG_VERSION: $(git ls-remote --tags origin 'refs/tags/npm-publish/*' | sort -t '/' -k 3 -V | tail -n 1 | awk -F/ '{print $NF}')

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Checkout tag 
        uses: actions/checkout@v3
        with:
          ref: npm-publish/${{ env.TAG_VERSION }}

      # # 2. Node.js 환경 설정
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.x'
      #     registry-url: 'https://registry.npmjs.org/wemixplay-ui'
      #     always-auth: true # 인증 항상 활성화

      # 3. npm 인증 정보 설정
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/wemixplay-ui:_authToken=${{ secrets.DEREK_NPM_TOKEN }}" > ./.npmrc

      # 4. Dependencies 설치 및 빌드
      - name: Install dependencies
        run: |
          yarn install
          yarn build

      # 5. npm 패키지 배포
      - name: Publish to npm
        run: yarn publish-version -- ${{ env.TAG_VERSION }} && yarn publish

              # 7. 태그 삭제
      - name: Delete tag locally and remotely
        run: |
          git tag -d ${{ env.TAG_VERSION }}
          git push origin :refs/tags/${{ env.TAG_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup .npmrc
        run: rm -f ./.npmrc

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
