name: Publish to npm

on:
  push:
    tags:
      - 'npm-publish/*'

jobs:
  publish:
    runs-on: self-hosted 

    steps:
      # 현재 트리거된 태그 이름을 직접 가져오기
      - name: Get tag name
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/npm-publish/}" >> $GITHUB_ENV

      # 1. 리포지토리 코드 체크아웃
      - name: Checkout tag 
        uses: actions/checkout@v3
        with:
          ref: refs/tags/npm-publish/${{ env.TAG_VERSION }}

      # 1. 리포지토리 코드 체크아웃
      - name: Checkout tag 
        uses: actions/checkout@v3
        with:
          ref: npm-publish/${{ env.TAG_VERSION }}

      # 3. npm 인증 정보 설정
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/wemixplay-ui:_authToken=${{ secrets.DEREK_NPM_TOKEN }}" > ./.npmrc

      # 4. Dependencies 설치 및 빌드
      - name: Install dependencies
        run: |
          yarn --ignore-platform
          yarn build

      # 5. npm 패키지 배포
      - name: Publish to npm
        run: yarn publish --new-version ${{ env.TAG_VERSION }}

              # 7. 태그 삭제
      - name: Delete tag locally and remotely
        run: |
          git tag -d ${{ env.TAG_VERSION }}
          git push origin :refs/tags/npm-publish/${{ env.TAG_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup .npmrc
        run: rm -f ./.npmrc

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
