name: Update PR Title and Description

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-pr:
    runs-on: self-hosted
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set PR title and description
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_BRANCH=$(echo "${{ github.event.pull_request.head.ref }}")
        BASE_BRANCH=$(echo "${{ github.event.pull_request.base.ref }}")
        PR_NUMBER=${{ github.event.pull_request.number }}

        if [ "$BASE_BRANCH" = "storybook" ]; then
          TITLE="스토리북 최신화"
          DESCRIPTION=$(git log -1 --pretty=format:"%h - %s")
        elif [ "$BASE_BRANCH" = "main" ]; then
          TITLE="정식 버전 소스 최신화"
          DESCRIPTION=$(git log -1 --pretty=format:"%h - %s")
        else
          exit 0
        fi

        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
          -d "{\"title\":\"$TITLE\", \"body\":\"$DESCRIPTION\"}"