name: Restrict Storybook Branch PRs

on:
  pull_request:
    branches:
      - storybook

jobs:
  restrict-pr:
    runs-on: self-hosted
    steps:
      - name: Check PR source branch
        if: github.event.pull_request.head.ref == 'alpha' || github.event.pull_request.head.ref == 'main'
        run: echo "PR from alpha or main branch is allowed."
      - name: Fail if not from alpha or main
        if: github.event.pull_request.head.ref != 'alpha' && github.event.pull_request.head.ref != 'main'
        run: |
          echo "PRs from branches other than alpha or main are not allowed."
          exit 1