name: Deploy to Remote Server via Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted # Self-hosted Runner 사용

    steps:
      - name: Move to Project
        run: cd ~/front-end/src/wemixplay-ui/storybook

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies and build
        run: |
          yarn --ignore-platform
          yarn build

      - name: Deploy to Application Directory
        run: git pull origin main
