name: Storybook Build And Deploy

on:
  push:
    branches:
      - storybook

jobs:
  storybook-build-and-deploy:
    runs-on: self-hosted 

    env:
      STORYBOOK_DIR: /home/alpha/front-end/src/wemixplay-ui/storybook

    defaults:
      run:
        working-directory: ${{ env.STORYBOOK_DIR }}

    steps:
      - name: Checkout storybook branch
        uses: actions/checkout@v3
        with:
          ref: storybook

      - name: Checkout storybook branch
        run: git checkout storybook

      - name: Install dependencies and build
        run: yarn build-storybook

      - name: Post Checkout main branch
        run: git checkout main
