name: Storybook Rebuild And Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted # Self-hosted Runner 사용

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git Pull
        run: git pull origin main

      - name: Move to Storybook Project
        run: cd storybook

      - name: Install dependencies and build
        run: |
          yarn build-storybook
