name: Deploy to Remote Server via Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted # Self-hosted Runner 사용

    steps:
      - name: Move to Project
        run: cd ~/front-end/src/wemixplay-ui/storybook

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git Pull
        run: git pull origin main

      - name: Install dependencies and build
        run: |
          yarn --ignore-platform
          yarn build-storybook
