name: Storybook Build And Deploy

on:
  push:
    branches:
      - storybook
  pull_request:
    types: [closed]
    branches:
      - storybook

jobs:
  storybook-build-and-deploy:
    runs-on: self-hosted 

    env:
      STORYBOOK_DIR: /home/alpha/front-end/src/wemixplay-ui/storybook

    defaults:
      run:
        working-directory: ${{ env.STORYBOOK_DIR }}

    steps:
      - name: Backup current storybook-static
        run: |
          if [ -d "storybook-static.backup" ]; then
            rm -rf storybook-static.backup
          fi
          if [ -d "storybook-static" ]; then
            cp -r storybook-static storybook-static.backup
          fi

      - name: Checkout storybook branch
        run: git checkout storybook

      - name: Install dependencies and build
        id: build
        run: yarn build-storybook
        continue-on-error: true

      - name: Rollback if build fails
        if: steps.build.outcome == 'failure'
        run: |
          if [ -d "storybook-static.backup" ]; then
            rm -rf storybook-static
            rename storybook-static.backup storybook-static
          fi
          echo "빌드 실패로 인한 롤백 수행"

      - name: Post Checkout main branch
        run: |
          git checkout main
