name: Storybook Rebuild And Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    defaults:
      run:
        working-directory: ~/front-end/src/wemixplay-ui/storybook

    steps:
      - name: Move to Storybook Project
        run: cd ~/front-end/src/wemixplay-ui/storybook

      - name: Git Pull
        run: git pull origin main

      - name: Install dependencies and build
        run: yarn build-storybook
